# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/genr8eofl/src/megaminx

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/genr8eofl/src/megaminx

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/genr8eofl/src/megaminx/CMakeFiles /home/genr8eofl/src/megaminx//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/genr8eofl/src/megaminx/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Megaminx

# Build rule for target.
Megaminx: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Megaminx
.PHONY : Megaminx

# fast build rule for target.
Megaminx/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Megaminx.dir/build.make CMakeFiles/Megaminx.dir/build
.PHONY : Megaminx/fast

src/engine/center.o: src/engine/center.cpp.o
.PHONY : src/engine/center.o

# target to build an object file
src/engine/center.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Megaminx.dir/build.make CMakeFiles/Megaminx.dir/src/engine/center.cpp.o
.PHONY : src/engine/center.cpp.o

src/engine/center.i: src/engine/center.cpp.i
.PHONY : src/engine/center.i

# target to preprocess a source file
src/engine/center.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Megaminx.dir/build.make CMakeFiles/Megaminx.dir/src/engine/center.cpp.i
.PHONY : src/engine/center.cpp.i

src/engine/center.s: src/engine/center.cpp.s
.PHONY : src/engine/center.s

# target to generate assembly for a file
src/engine/center.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Megaminx.dir/build.make CMakeFiles/Megaminx.dir/src/engine/center.cpp.s
.PHONY : src/engine/center.cpp.s

src/engine/corner.o: src/engine/corner.cpp.o
.PHONY : src/engine/corner.o

# target to build an object file
src/engine/corner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Megaminx.dir/build.make CMakeFiles/Megaminx.dir/src/engine/corner.cpp.o
.PHONY : src/engine/corner.cpp.o

src/engine/corner.i: src/engine/corner.cpp.i
.PHONY : src/engine/corner.i

# target to preprocess a source file
src/engine/corner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Megaminx.dir/build.make CMakeFiles/Megaminx.dir/src/engine/corner.cpp.i
.PHONY : src/engine/corner.cpp.i

src/engine/corner.s: src/engine/corner.cpp.s
.PHONY : src/engine/corner.s

# target to generate assembly for a file
src/engine/corner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Megaminx.dir/build.make CMakeFiles/Megaminx.dir/src/engine/corner.cpp.s
.PHONY : src/engine/corner.cpp.s

src/engine/edge.o: src/engine/edge.cpp.o
.PHONY : src/engine/edge.o

# target to build an object file
src/engine/edge.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Megaminx.dir/build.make CMakeFiles/Megaminx.dir/src/engine/edge.cpp.o
.PHONY : src/engine/edge.cpp.o

src/engine/edge.i: src/engine/edge.cpp.i
.PHONY : src/engine/edge.i

# target to preprocess a source file
src/engine/edge.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Megaminx.dir/build.make CMakeFiles/Megaminx.dir/src/engine/edge.cpp.i
.PHONY : src/engine/edge.cpp.i

src/engine/edge.s: src/engine/edge.cpp.s
.PHONY : src/engine/edge.s

# target to generate assembly for a file
src/engine/edge.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Megaminx.dir/build.make CMakeFiles/Megaminx.dir/src/engine/edge.cpp.s
.PHONY : src/engine/edge.cpp.s

src/engine/face.o: src/engine/face.cpp.o
.PHONY : src/engine/face.o

# target to build an object file
src/engine/face.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Megaminx.dir/build.make CMakeFiles/Megaminx.dir/src/engine/face.cpp.o
.PHONY : src/engine/face.cpp.o

src/engine/face.i: src/engine/face.cpp.i
.PHONY : src/engine/face.i

# target to preprocess a source file
src/engine/face.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Megaminx.dir/build.make CMakeFiles/Megaminx.dir/src/engine/face.cpp.i
.PHONY : src/engine/face.cpp.i

src/engine/face.s: src/engine/face.cpp.s
.PHONY : src/engine/face.s

# target to generate assembly for a file
src/engine/face.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Megaminx.dir/build.make CMakeFiles/Megaminx.dir/src/engine/face.cpp.s
.PHONY : src/engine/face.cpp.s

src/engine/load.o: src/engine/load.cpp.o
.PHONY : src/engine/load.o

# target to build an object file
src/engine/load.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Megaminx.dir/build.make CMakeFiles/Megaminx.dir/src/engine/load.cpp.o
.PHONY : src/engine/load.cpp.o

src/engine/load.i: src/engine/load.cpp.i
.PHONY : src/engine/load.i

# target to preprocess a source file
src/engine/load.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Megaminx.dir/build.make CMakeFiles/Megaminx.dir/src/engine/load.cpp.i
.PHONY : src/engine/load.cpp.i

src/engine/load.s: src/engine/load.cpp.s
.PHONY : src/engine/load.s

# target to generate assembly for a file
src/engine/load.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Megaminx.dir/build.make CMakeFiles/Megaminx.dir/src/engine/load.cpp.s
.PHONY : src/engine/load.cpp.s

src/engine/megaminx.o: src/engine/megaminx.cpp.o
.PHONY : src/engine/megaminx.o

# target to build an object file
src/engine/megaminx.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Megaminx.dir/build.make CMakeFiles/Megaminx.dir/src/engine/megaminx.cpp.o
.PHONY : src/engine/megaminx.cpp.o

src/engine/megaminx.i: src/engine/megaminx.cpp.i
.PHONY : src/engine/megaminx.i

# target to preprocess a source file
src/engine/megaminx.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Megaminx.dir/build.make CMakeFiles/Megaminx.dir/src/engine/megaminx.cpp.i
.PHONY : src/engine/megaminx.cpp.i

src/engine/megaminx.s: src/engine/megaminx.cpp.s
.PHONY : src/engine/megaminx.s

# target to generate assembly for a file
src/engine/megaminx.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Megaminx.dir/build.make CMakeFiles/Megaminx.dir/src/engine/megaminx.cpp.s
.PHONY : src/engine/megaminx.cpp.s

src/engine/shadow.o: src/engine/shadow.cpp.o
.PHONY : src/engine/shadow.o

# target to build an object file
src/engine/shadow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Megaminx.dir/build.make CMakeFiles/Megaminx.dir/src/engine/shadow.cpp.o
.PHONY : src/engine/shadow.cpp.o

src/engine/shadow.i: src/engine/shadow.cpp.i
.PHONY : src/engine/shadow.i

# target to preprocess a source file
src/engine/shadow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Megaminx.dir/build.make CMakeFiles/Megaminx.dir/src/engine/shadow.cpp.i
.PHONY : src/engine/shadow.cpp.i

src/engine/shadow.s: src/engine/shadow.cpp.s
.PHONY : src/engine/shadow.s

# target to generate assembly for a file
src/engine/shadow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Megaminx.dir/build.make CMakeFiles/Megaminx.dir/src/engine/shadow.cpp.s
.PHONY : src/engine/shadow.cpp.s

src/engine/solve.o: src/engine/solve.cpp.o
.PHONY : src/engine/solve.o

# target to build an object file
src/engine/solve.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Megaminx.dir/build.make CMakeFiles/Megaminx.dir/src/engine/solve.cpp.o
.PHONY : src/engine/solve.cpp.o

src/engine/solve.i: src/engine/solve.cpp.i
.PHONY : src/engine/solve.i

# target to preprocess a source file
src/engine/solve.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Megaminx.dir/build.make CMakeFiles/Megaminx.dir/src/engine/solve.cpp.i
.PHONY : src/engine/solve.cpp.i

src/engine/solve.s: src/engine/solve.cpp.s
.PHONY : src/engine/solve.s

# target to generate assembly for a file
src/engine/solve.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Megaminx.dir/build.make CMakeFiles/Megaminx.dir/src/engine/solve.cpp.s
.PHONY : src/engine/solve.cpp.s

src/main-menu.o: src/main-menu.cpp.o
.PHONY : src/main-menu.o

# target to build an object file
src/main-menu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Megaminx.dir/build.make CMakeFiles/Megaminx.dir/src/main-menu.cpp.o
.PHONY : src/main-menu.cpp.o

src/main-menu.i: src/main-menu.cpp.i
.PHONY : src/main-menu.i

# target to preprocess a source file
src/main-menu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Megaminx.dir/build.make CMakeFiles/Megaminx.dir/src/main-menu.cpp.i
.PHONY : src/main-menu.cpp.i

src/main-menu.s: src/main-menu.cpp.s
.PHONY : src/main-menu.s

# target to generate assembly for a file
src/main-menu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Megaminx.dir/build.make CMakeFiles/Megaminx.dir/src/main-menu.cpp.s
.PHONY : src/main-menu.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Megaminx.dir/build.make CMakeFiles/Megaminx.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Megaminx.dir/build.make CMakeFiles/Megaminx.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Megaminx.dir/build.make CMakeFiles/Megaminx.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/readline.o: src/readline.cpp.o
.PHONY : src/readline.o

# target to build an object file
src/readline.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Megaminx.dir/build.make CMakeFiles/Megaminx.dir/src/readline.cpp.o
.PHONY : src/readline.cpp.o

src/readline.i: src/readline.cpp.i
.PHONY : src/readline.i

# target to preprocess a source file
src/readline.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Megaminx.dir/build.make CMakeFiles/Megaminx.dir/src/readline.cpp.i
.PHONY : src/readline.cpp.i

src/readline.s: src/readline.cpp.s
.PHONY : src/readline.s

# target to generate assembly for a file
src/readline.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Megaminx.dir/build.make CMakeFiles/Megaminx.dir/src/readline.cpp.s
.PHONY : src/readline.cpp.s

src/ui/camera.o: src/ui/camera.cpp.o
.PHONY : src/ui/camera.o

# target to build an object file
src/ui/camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Megaminx.dir/build.make CMakeFiles/Megaminx.dir/src/ui/camera.cpp.o
.PHONY : src/ui/camera.cpp.o

src/ui/camera.i: src/ui/camera.cpp.i
.PHONY : src/ui/camera.i

# target to preprocess a source file
src/ui/camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Megaminx.dir/build.make CMakeFiles/Megaminx.dir/src/ui/camera.cpp.i
.PHONY : src/ui/camera.cpp.i

src/ui/camera.s: src/ui/camera.cpp.s
.PHONY : src/ui/camera.s

# target to generate assembly for a file
src/ui/camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Megaminx.dir/build.make CMakeFiles/Megaminx.dir/src/ui/camera.cpp.s
.PHONY : src/ui/camera.cpp.s

src/ui/linenoise.o: src/ui/linenoise.c.o
.PHONY : src/ui/linenoise.o

# target to build an object file
src/ui/linenoise.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Megaminx.dir/build.make CMakeFiles/Megaminx.dir/src/ui/linenoise.c.o
.PHONY : src/ui/linenoise.c.o

src/ui/linenoise.i: src/ui/linenoise.c.i
.PHONY : src/ui/linenoise.i

# target to preprocess a source file
src/ui/linenoise.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Megaminx.dir/build.make CMakeFiles/Megaminx.dir/src/ui/linenoise.c.i
.PHONY : src/ui/linenoise.c.i

src/ui/linenoise.s: src/ui/linenoise.c.s
.PHONY : src/ui/linenoise.s

# target to generate assembly for a file
src/ui/linenoise.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Megaminx.dir/build.make CMakeFiles/Megaminx.dir/src/ui/linenoise.c.s
.PHONY : src/ui/linenoise.c.s

src/ui/opengl.o: src/ui/opengl.cpp.o
.PHONY : src/ui/opengl.o

# target to build an object file
src/ui/opengl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Megaminx.dir/build.make CMakeFiles/Megaminx.dir/src/ui/opengl.cpp.o
.PHONY : src/ui/opengl.cpp.o

src/ui/opengl.i: src/ui/opengl.cpp.i
.PHONY : src/ui/opengl.i

# target to preprocess a source file
src/ui/opengl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Megaminx.dir/build.make CMakeFiles/Megaminx.dir/src/ui/opengl.cpp.i
.PHONY : src/ui/opengl.cpp.i

src/ui/opengl.s: src/ui/opengl.cpp.s
.PHONY : src/ui/opengl.s

# target to generate assembly for a file
src/ui/opengl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Megaminx.dir/build.make CMakeFiles/Megaminx.dir/src/ui/opengl.cpp.s
.PHONY : src/ui/opengl.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Megaminx"
	@echo "... src/engine/center.o"
	@echo "... src/engine/center.i"
	@echo "... src/engine/center.s"
	@echo "... src/engine/corner.o"
	@echo "... src/engine/corner.i"
	@echo "... src/engine/corner.s"
	@echo "... src/engine/edge.o"
	@echo "... src/engine/edge.i"
	@echo "... src/engine/edge.s"
	@echo "... src/engine/face.o"
	@echo "... src/engine/face.i"
	@echo "... src/engine/face.s"
	@echo "... src/engine/load.o"
	@echo "... src/engine/load.i"
	@echo "... src/engine/load.s"
	@echo "... src/engine/megaminx.o"
	@echo "... src/engine/megaminx.i"
	@echo "... src/engine/megaminx.s"
	@echo "... src/engine/shadow.o"
	@echo "... src/engine/shadow.i"
	@echo "... src/engine/shadow.s"
	@echo "... src/engine/solve.o"
	@echo "... src/engine/solve.i"
	@echo "... src/engine/solve.s"
	@echo "... src/main-menu.o"
	@echo "... src/main-menu.i"
	@echo "... src/main-menu.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/readline.o"
	@echo "... src/readline.i"
	@echo "... src/readline.s"
	@echo "... src/ui/camera.o"
	@echo "... src/ui/camera.i"
	@echo "... src/ui/camera.s"
	@echo "... src/ui/linenoise.o"
	@echo "... src/ui/linenoise.i"
	@echo "... src/ui/linenoise.s"
	@echo "... src/ui/opengl.o"
	@echo "... src/ui/opengl.i"
	@echo "... src/ui/opengl.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

