# CMAKE generated file: DO NOT EDIT!
# Generated by "MSYS Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /C/Software/msys64/mingw64/bin/cmake.exe

# The command to remove a file.
RM = /C/Software/msys64/mingw64/bin/cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /C/Users/EOFL/Source/Repos/megaminx

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /C/Users/EOFL/Source/Repos/megaminx

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/C/Software/msys64/mingw64/bin/cmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/C/Software/msys64/mingw64/bin/cmake-gui.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /C/Users/EOFL/Source/Repos/megaminx/CMakeFiles /C/Users/EOFL/Source/Repos/megaminx/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /C/Users/EOFL/Source/Repos/megaminx/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MegaMinx2

# Build rule for target.
MegaMinx2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MegaMinx2
.PHONY : MegaMinx2

# fast build rule for target.
MegaMinx2/fast:
	$(MAKE) -f CMakeFiles/MegaMinx2.dir/build.make CMakeFiles/MegaMinx2.dir/build
.PHONY : MegaMinx2/fast

Res.obj: Res.rc.obj

.PHONY : Res.obj

# target to build an object file
Res.rc.obj:
	$(MAKE) -f CMakeFiles/MegaMinx2.dir/build.make CMakeFiles/MegaMinx2.dir/Res.rc.obj
.PHONY : Res.rc.obj

common_physics/camera.obj: common_physics/camera.cpp.obj

.PHONY : common_physics/camera.obj

# target to build an object file
common_physics/camera.cpp.obj:
	$(MAKE) -f CMakeFiles/MegaMinx2.dir/build.make CMakeFiles/MegaMinx2.dir/common_physics/camera.cpp.obj
.PHONY : common_physics/camera.cpp.obj

common_physics/camera.i: common_physics/camera.cpp.i

.PHONY : common_physics/camera.i

# target to preprocess a source file
common_physics/camera.cpp.i:
	$(MAKE) -f CMakeFiles/MegaMinx2.dir/build.make CMakeFiles/MegaMinx2.dir/common_physics/camera.cpp.i
.PHONY : common_physics/camera.cpp.i

common_physics/camera.s: common_physics/camera.cpp.s

.PHONY : common_physics/camera.s

# target to generate assembly for a file
common_physics/camera.cpp.s:
	$(MAKE) -f CMakeFiles/MegaMinx2.dir/build.make CMakeFiles/MegaMinx2.dir/common_physics/camera.cpp.s
.PHONY : common_physics/camera.cpp.s

common_physics/opengl.obj: common_physics/opengl.cpp.obj

.PHONY : common_physics/opengl.obj

# target to build an object file
common_physics/opengl.cpp.obj:
	$(MAKE) -f CMakeFiles/MegaMinx2.dir/build.make CMakeFiles/MegaMinx2.dir/common_physics/opengl.cpp.obj
.PHONY : common_physics/opengl.cpp.obj

common_physics/opengl.i: common_physics/opengl.cpp.i

.PHONY : common_physics/opengl.i

# target to preprocess a source file
common_physics/opengl.cpp.i:
	$(MAKE) -f CMakeFiles/MegaMinx2.dir/build.make CMakeFiles/MegaMinx2.dir/common_physics/opengl.cpp.i
.PHONY : common_physics/opengl.cpp.i

common_physics/opengl.s: common_physics/opengl.cpp.s

.PHONY : common_physics/opengl.s

# target to generate assembly for a file
common_physics/opengl.cpp.s:
	$(MAKE) -f CMakeFiles/MegaMinx2.dir/build.make CMakeFiles/MegaMinx2.dir/common_physics/opengl.cpp.s
.PHONY : common_physics/opengl.cpp.s

common_physics/raytri.obj: common_physics/raytri.cpp.obj

.PHONY : common_physics/raytri.obj

# target to build an object file
common_physics/raytri.cpp.obj:
	$(MAKE) -f CMakeFiles/MegaMinx2.dir/build.make CMakeFiles/MegaMinx2.dir/common_physics/raytri.cpp.obj
.PHONY : common_physics/raytri.cpp.obj

common_physics/raytri.i: common_physics/raytri.cpp.i

.PHONY : common_physics/raytri.i

# target to preprocess a source file
common_physics/raytri.cpp.i:
	$(MAKE) -f CMakeFiles/MegaMinx2.dir/build.make CMakeFiles/MegaMinx2.dir/common_physics/raytri.cpp.i
.PHONY : common_physics/raytri.cpp.i

common_physics/raytri.s: common_physics/raytri.cpp.s

.PHONY : common_physics/raytri.s

# target to generate assembly for a file
common_physics/raytri.cpp.s:
	$(MAKE) -f CMakeFiles/MegaMinx2.dir/build.make CMakeFiles/MegaMinx2.dir/common_physics/raytri.cpp.s
.PHONY : common_physics/raytri.cpp.s

engine/center.obj: engine/center.cpp.obj

.PHONY : engine/center.obj

# target to build an object file
engine/center.cpp.obj:
	$(MAKE) -f CMakeFiles/MegaMinx2.dir/build.make CMakeFiles/MegaMinx2.dir/engine/center.cpp.obj
.PHONY : engine/center.cpp.obj

engine/center.i: engine/center.cpp.i

.PHONY : engine/center.i

# target to preprocess a source file
engine/center.cpp.i:
	$(MAKE) -f CMakeFiles/MegaMinx2.dir/build.make CMakeFiles/MegaMinx2.dir/engine/center.cpp.i
.PHONY : engine/center.cpp.i

engine/center.s: engine/center.cpp.s

.PHONY : engine/center.s

# target to generate assembly for a file
engine/center.cpp.s:
	$(MAKE) -f CMakeFiles/MegaMinx2.dir/build.make CMakeFiles/MegaMinx2.dir/engine/center.cpp.s
.PHONY : engine/center.cpp.s

engine/corner.obj: engine/corner.cpp.obj

.PHONY : engine/corner.obj

# target to build an object file
engine/corner.cpp.obj:
	$(MAKE) -f CMakeFiles/MegaMinx2.dir/build.make CMakeFiles/MegaMinx2.dir/engine/corner.cpp.obj
.PHONY : engine/corner.cpp.obj

engine/corner.i: engine/corner.cpp.i

.PHONY : engine/corner.i

# target to preprocess a source file
engine/corner.cpp.i:
	$(MAKE) -f CMakeFiles/MegaMinx2.dir/build.make CMakeFiles/MegaMinx2.dir/engine/corner.cpp.i
.PHONY : engine/corner.cpp.i

engine/corner.s: engine/corner.cpp.s

.PHONY : engine/corner.s

# target to generate assembly for a file
engine/corner.cpp.s:
	$(MAKE) -f CMakeFiles/MegaMinx2.dir/build.make CMakeFiles/MegaMinx2.dir/engine/corner.cpp.s
.PHONY : engine/corner.cpp.s

engine/edge.obj: engine/edge.cpp.obj

.PHONY : engine/edge.obj

# target to build an object file
engine/edge.cpp.obj:
	$(MAKE) -f CMakeFiles/MegaMinx2.dir/build.make CMakeFiles/MegaMinx2.dir/engine/edge.cpp.obj
.PHONY : engine/edge.cpp.obj

engine/edge.i: engine/edge.cpp.i

.PHONY : engine/edge.i

# target to preprocess a source file
engine/edge.cpp.i:
	$(MAKE) -f CMakeFiles/MegaMinx2.dir/build.make CMakeFiles/MegaMinx2.dir/engine/edge.cpp.i
.PHONY : engine/edge.cpp.i

engine/edge.s: engine/edge.cpp.s

.PHONY : engine/edge.s

# target to generate assembly for a file
engine/edge.cpp.s:
	$(MAKE) -f CMakeFiles/MegaMinx2.dir/build.make CMakeFiles/MegaMinx2.dir/engine/edge.cpp.s
.PHONY : engine/edge.cpp.s

engine/face.obj: engine/face.cpp.obj

.PHONY : engine/face.obj

# target to build an object file
engine/face.cpp.obj:
	$(MAKE) -f CMakeFiles/MegaMinx2.dir/build.make CMakeFiles/MegaMinx2.dir/engine/face.cpp.obj
.PHONY : engine/face.cpp.obj

engine/face.i: engine/face.cpp.i

.PHONY : engine/face.i

# target to preprocess a source file
engine/face.cpp.i:
	$(MAKE) -f CMakeFiles/MegaMinx2.dir/build.make CMakeFiles/MegaMinx2.dir/engine/face.cpp.i
.PHONY : engine/face.cpp.i

engine/face.s: engine/face.cpp.s

.PHONY : engine/face.s

# target to generate assembly for a file
engine/face.cpp.s:
	$(MAKE) -f CMakeFiles/MegaMinx2.dir/build.make CMakeFiles/MegaMinx2.dir/engine/face.cpp.s
.PHONY : engine/face.cpp.s

engine/megaminx.obj: engine/megaminx.cpp.obj

.PHONY : engine/megaminx.obj

# target to build an object file
engine/megaminx.cpp.obj:
	$(MAKE) -f CMakeFiles/MegaMinx2.dir/build.make CMakeFiles/MegaMinx2.dir/engine/megaminx.cpp.obj
.PHONY : engine/megaminx.cpp.obj

engine/megaminx.i: engine/megaminx.cpp.i

.PHONY : engine/megaminx.i

# target to preprocess a source file
engine/megaminx.cpp.i:
	$(MAKE) -f CMakeFiles/MegaMinx2.dir/build.make CMakeFiles/MegaMinx2.dir/engine/megaminx.cpp.i
.PHONY : engine/megaminx.cpp.i

engine/megaminx.s: engine/megaminx.cpp.s

.PHONY : engine/megaminx.s

# target to generate assembly for a file
engine/megaminx.cpp.s:
	$(MAKE) -f CMakeFiles/MegaMinx2.dir/build.make CMakeFiles/MegaMinx2.dir/engine/megaminx.cpp.s
.PHONY : engine/megaminx.cpp.s

engine/utils.obj: engine/utils.cpp.obj

.PHONY : engine/utils.obj

# target to build an object file
engine/utils.cpp.obj:
	$(MAKE) -f CMakeFiles/MegaMinx2.dir/build.make CMakeFiles/MegaMinx2.dir/engine/utils.cpp.obj
.PHONY : engine/utils.cpp.obj

engine/utils.i: engine/utils.cpp.i

.PHONY : engine/utils.i

# target to preprocess a source file
engine/utils.cpp.i:
	$(MAKE) -f CMakeFiles/MegaMinx2.dir/build.make CMakeFiles/MegaMinx2.dir/engine/utils.cpp.i
.PHONY : engine/utils.cpp.i

engine/utils.s: engine/utils.cpp.s

.PHONY : engine/utils.s

# target to generate assembly for a file
engine/utils.cpp.s:
	$(MAKE) -f CMakeFiles/MegaMinx2.dir/build.make CMakeFiles/MegaMinx2.dir/engine/utils.cpp.s
.PHONY : engine/utils.cpp.s

main.obj: main.cpp.obj

.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) -f CMakeFiles/MegaMinx2.dir/build.make CMakeFiles/MegaMinx2.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/MegaMinx2.dir/build.make CMakeFiles/MegaMinx2.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/MegaMinx2.dir/build.make CMakeFiles/MegaMinx2.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... MegaMinx2"
	@echo "... edit_cache"
	@echo "... Res.obj"
	@echo "... common_physics/camera.obj"
	@echo "... common_physics/camera.i"
	@echo "... common_physics/camera.s"
	@echo "... common_physics/opengl.obj"
	@echo "... common_physics/opengl.i"
	@echo "... common_physics/opengl.s"
	@echo "... common_physics/raytri.obj"
	@echo "... common_physics/raytri.i"
	@echo "... common_physics/raytri.s"
	@echo "... engine/center.obj"
	@echo "... engine/center.i"
	@echo "... engine/center.s"
	@echo "... engine/corner.obj"
	@echo "... engine/corner.i"
	@echo "... engine/corner.s"
	@echo "... engine/edge.obj"
	@echo "... engine/edge.i"
	@echo "... engine/edge.s"
	@echo "... engine/face.obj"
	@echo "... engine/face.i"
	@echo "... engine/face.s"
	@echo "... engine/megaminx.obj"
	@echo "... engine/megaminx.i"
	@echo "... engine/megaminx.s"
	@echo "... engine/utils.obj"
	@echo "... engine/utils.i"
	@echo "... engine/utils.s"
	@echo "... main.obj"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

